Port 8090
BindAddress 0.0.0.0
MaxClients 5
MaxBandwidth 1000
NoDaemon

<Feed wcam.ffm>
	File /tmp/wcam.ffm
	FileMaxSize 5M
	ACL allow 127.0.0.1
</Feed>

<Stream wcam.mjpeg>
	Format mjpeg
	Feed wcam.ffm

	VideoFrameRate 15
	VideoBitRate 500
	VideoSize 352x288
	VideoQMin 1
	VideoQMax 10

	NoAudio
</Stream>

